### ISSUE TITLE
check_singlebam.pyで一部データが既にあるとき

### ISSUE THREAD

**Issue by friend1ws** [aokad/GenomonTCGAkit#2]
今って一部データがあっても、とりあえずまず消して、
全部やり直す仕様になっているという理解で良いですかね？？

これは例えば、
STAD_000が終わって、check, genomonをかけて、
そのあとにSTAD_001の分を実行するというときに、
STAD_000の分ももう一度やらなくてはならないということですかね？？

大した計算ではないので、別に良いかもしれないですが、
一応確認したいです。

**Comment by aokad** [comment]
修正しました。

**Comment by friend1ws** [comment]
了解です。
